# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'

use_frameworks!
	
  def app_pods
      pod 'Alamofire', '4.8.0'
      pod 'SwiftyJSON', '~> 4.0'
      pod 'ReachabilitySwift', '4.3.1'
      pod 'SVProgressHUD'
      pod 'R.swift', '5.0.2'
      pod 'PureLayout', '~> 3.0.2'

      # UI
      pod 'LBTATools', :git => 'https://github.com/johnrichard23/LBTATools'
      pod 'XLPagerTabStrip', '8.1'
      pod 'MaterialComponents/TextFields'
      pod 'Popover', '1.2.1'

      # Rx
      pod 'RxSwift', '~> 5'
      pod 'RxSwiftExt', '~> 5'
      pod 'NSObject+Rx', '~> 5'
  end

  def testing_pods
      pod 'Quick', '~> 2.1.0'
      pod 'Nimble', '~> 8.0.2'
      pod 'Mockingjay', '~> 2.0.1'
  end

  target 'NewsApp' do
      app_pods
  end

  target 'NewsAppTests' do
      app_pods
      testing_pods
  end
